### ISSUE TITLE
[top] Re-organize reset domains

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15317]
The current reset domain organization, specifically the `lc` and `sys` resets, cause a lot of cross domain communication that becomes difficult to manage when `ndm_reset` is requested. 

This leads to potentially a lot of instability in the debug module usage and would become problematic on silicon. 
This [proposal](https://docs.google.com/presentation/d/1kDKSQTSYhP-Q9GoQLcmapb00ovSeLP6lZ4l0lBfxW18/edit?usp=sharing) outlines a different way to handle the reset domains such that it has significantly fewer cross domain signals.  This will then improve the usability of stability of the rv_dm domain. 

fixes #14287 
fixes #14086

Will be fixed by #15602

**Comment by tjaychen** [comment]
@matutem 
@sriyerg 
@cdgori 
@alphan 
@dmcardle 
@a-will

**Comment by Jacob-Levy** [comment]
@tjaychen This looks like the issue with the resets I had with `prim_pulse_sync` which I fixed with new cell I added, `ast_pulse_sync`.

**Comment by tjaychen** [comment]
It's very similar but it isn't exactly the same issue. This issue here specifically relates to `ndm` triggered resets. I think the one in your situation was a bit different.
We are still addressing this from an instantiator level, just that this one is a complete re-organization of the `ndm` case.

We actually investigated the path of placing the cross reset directly in the module, but actually identified a lot of drawbacks. So likely in the future we are going to add assertions to force the instantiator of the modules to deal with it.

**Comment by tjaychen** [comment]
To elaborate a bit more. What we noticed with modules like these is that even if have the resets affect each other, the upstream / downstream logic is still broken a lot of times.  Ie, even if both sides of the `prim_pulse_sync` reset, it doesn't really help since the upstream that initiated the request effectively "lost" its request.  So we don't want the cross reset to give the illusion of solving the problem.  So instead we will likely opt for a version that asserts a failure if this situation occurs, and force the instantiator to deal with it.

The second point you made is valid.  The pulse modules do not back-pressure and will break when a new pulse shows up.  I believe we have also added an assertion for this behavior.   I guess I'm not completely clear on why you feel an assert is not sufficient. It is true in synthesized code there will be no ASSERT, but isn't that why we do simulations and have equivalency checks? Or are you concerned about simulations not having enough coverage? Because by this logic none of our assertions are valuable, since they would all disappear after synthesis.

**Comment by Jacob-Levy** [comment]
@tjaychen I understand your analysis for the two issues. 
In the AST case, I back-pressured the source pulse to solve the second issue while maintaining the ASSERT  in place.
As for the resets, loosing a pulse was less significant the breaking the function of the cell.
Most likely, the reset asserted will take care for re-issueing the lost pulse, but it will be a good idea to issue a warning/add ASSERT to identify this condition.

**Comment by msfschaffner** [comment]
#15602 has been merged, so this issue can be closed.
