### ISSUE TITLE
[rv_timer] Separate reset for watchdog

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#398]
This is as much a question as it is a request.

I'm currently claiming that a normal timer and the watchdog timer sit on different reset domains. The idea is mostly we don't want someone to be able to reset the processing core and the watchdog together, which effectively silences the watchdog.  See diagram

[https://docs.google.com/drawings/d/1a3nkFVJhCFQUR9uQMm7Hfr2cSLGmaJ5HOuLX4ZyNkCY/edit](url)

If we agree that this the behavior that we want, then we'd either need rv_timer to support different resets (i think it was intended for watchdog?) or it might be easier if we just instantiate a separate rv timer for watchdog. 

This is not something that needs to be urgently discussed yet, but I just wanted to document it and see how people feel.

The link below also contains the thinking that went into the timer if it were 64b.
https://docs.google.com/drawings/d/1xyxdF5ZFSy5hz4reumzcU3PFcHfhgBmAoGqf5lgYnL0/edit?usp=sharing

**Comment by tjaychen** [comment]
sory for the late reply on this.. but yes i was originally thinking two timers. This area however, we might want to discuss a bit more with the software teams. There are specific behaviors they're looking for around low power, and it's not quite the same as standard rv timer.

**Comment by tjaychen** [comment]
@mateenfaisal @tomroberts-lowrisc 
this is a quick write-up we did on how we envision the timer to work.

Most of the bits are worked out, with the exception of how we should handle multiple NMIs in the system.  In order to ensure that the ROM isn't immediately interrupted upon wakeup, I am recommending another rv_plic-like module that handles the initial enabling of NMIs (this of course needs to be one-way, as in, once enabled we cannot revert it).

Please have a look.
https://docs.google.com/document/d/1EBA7Yg-k1eW61SQRSfiITTaiIwao6drwQOIPsf-mGdc/edit?usp=sharing

**Comment by msfschaffner** [comment]
Since we've implemented and instantiated a watchdog timer by now, we should be able to close this issue soon.
The only thing that remains to be done is to convert the regular IRQ coming from the watchdog to an NMI. 
See also comment here: https://github.com/lowRISC/opentitan/pull/7257#issuecomment-879389067

**Comment by tjaychen** [comment]
i'm still not sure our latest discussion actually wanted the watchdog to be an NMI.
I have some very vague recollections (i could be wrong) that it's okay to treat it as an interrupt.  If the interrupt is masked off (for whatever reason), the real watchdog will kick in anyhow.

**Comment by tjaychen** [comment]
i'll take an action to check with software again and actually document this somewhere.

**Comment by vogelpi** [comment]
> i'm still not sure our latest discussion actually wanted the watchdog to be an NMI.
> I have some very vague recollections (i could be wrong) that it's okay to treat it as an interrupt. If the interrupt is masked off (for whatever reason), the real watchdog will kick in anyhow.

That's also what I remember from these discussions!

**Comment by msfschaffner** [comment]
Hey @tjaychen, has this been documented somewhere so that we can close it?

**Comment by tjaychen** [comment]
yep, this can be closed.
